<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Testimonial extends Model
{
    use HasFactory, HasUuids;

    protected $table = 'testimonials';

    protected $fillable = [
        'user_id',
        'user_name',
        'user_role',
        'avatar',
        'message',
        'rating',
        'is_featured',
        'is_active',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function hasAvatar(): bool
    {
        return !empty($this->avatar);
    }

    public function getAvatarUrl(): string
    {
        if ($this->hasAvatar()) {
            return url($this->avatar);
        }

        return url('images/avatars/default-avatar.webp');
    }

    /**
     * Generate dynamic testimonial messages
     */
    public static function generateTestimonialMessages(int $count = 100): array
    {
        $openings = [
            "This gaming platform has revolutionized my approach to online slots.",
            "I've been using this platform for months now and I'm impressed by",
            "Outstanding platform! The premium tools have significantly",
            "Love the user-friendly interface and the vast collection of",
            "The accuracy of the RTP data here is unmatched.",
            "This platform stands out with its premium tools and",
            "Great platform for serious gamers! The tools are",
            "I've tried many gaming platforms, but this one offers",
            "The testimonial section is incredibly helpful for",
            "Professional-grade gaming tools with exceptional",
            "Absolutely amazing platform that has transformed my gaming experience!",
            "After extensive research, I found this platform to be",
            "I'm absolutely blown away by the quality of",
            "This is hands down the best gaming platform I've ever used.",
            "The level of detail and accuracy in this platform is",
            "I can't believe how comprehensive and well-designed",
            "My gaming strategy has completely changed thanks to",
            "This platform delivers exactly what serious gamers need:",
            "The community here is incredible, and the platform provides",
            "I've never seen such a well-thought-out gaming platform before.",
            "The real-time data and analytics on this platform are",
            "Every feature in this platform has been carefully crafted for",
            "This platform has exceeded all my expectations with its",
            "The attention to detail in every aspect of this platform is",
            "I've been a gamer for years, and this platform offers",
            "The intuitive design combined with powerful features makes",
            "This platform has become my secret weapon for",
            "I'm constantly amazed by the depth and quality of",
            "The seamless integration of all features in this platform",
            "This platform represents the future of gaming analytics with",
            "Every update brings new and exciting improvements to",
            "The dedication to quality is evident in every part of",
            "This platform has set a new standard for gaming tools with",
            "I'm impressed by how user-friendly yet powerful",
            "The comprehensive approach to gaming data on this platform",
            "This platform has everything a serious gamer could want:",
            "The real-time updates and accurate information provide",
            "I've tested many platforms, but this one stands apart with",
            "The community-driven features combined with professional tools",
            "This platform has revolutionized how I approach",
            "The seamless experience from start to finish on this platform",
            "I'm constantly discovering new ways to use",
            "The platform's commitment to accuracy is unmatched in",
            "Every tool and feature has been designed with",
            "This platform has become an essential part of my",
            "The depth of information available on this platform",
            "I'm amazed by how much thought went into",
            "The platform's ability to provide real-time insights",
            "This platform has transformed the way I think about",
            "The comprehensive database and accurate data make",
            "I'm impressed by the platform's dedication to",
            "The user experience on this platform is simply",
            "This platform has everything needed for serious gaming with",
            "The attention to detail in the design of",
            "I'm constantly surprised by the quality of",
            "The platform's comprehensive approach to gaming data",
            "This platform has set new standards with its",
            "The real-time analytics and accurate information",
            "I'm amazed by how comprehensive and accurate",
            "The platform's commitment to excellence shows in",
            "This platform has everything a professional gamer needs:",
            "The depth and quality of the gaming tools here",
            "I'm impressed by the platform's ability to deliver",
            "The comprehensive nature of this platform's features",
            "This platform has revolutionized gaming analytics with",
            "The attention to detail and accuracy throughout",
            "I'm constantly discovering new features in",
            "The platform's dedication to providing quality",
            "This platform represents the pinnacle of gaming tools with",
            "The seamless integration and powerful features of",
            "I'm amazed by the platform's comprehensive approach to",
            "The quality and accuracy of information on this platform",
            "This platform has exceeded my wildest expectations with",
            "The depth of features and attention to detail in",
            "I'm impressed by how well-designed and comprehensive",
            "The platform's commitment to real-time data and",
            "This platform has become my go-to resource for",
            "The comprehensive database and accurate analytics",
            "I'm amazed by the platform's dedication to excellence in",
            "The quality of every feature and tool on this platform",
            "This platform has set the gold standard for",
            "The attention to detail and comprehensive nature of",
            "I'm constantly impressed by the platform's ability to",
            "The real-time updates and accurate information make",
            "This platform has everything serious gamers need with",
            "The depth and quality of the gaming database here",
            "I'm amazed by how comprehensive and well-thought-out",
            "The platform's commitment to accuracy and quality shows in",
            "This platform represents the future of gaming with",
            "The seamless experience and powerful tools of",
            "I'm impressed by the platform's comprehensive database of",
            "The quality and depth of information available on",
            "This platform has transformed my gaming approach with",
            "The attention to detail in every feature of"
        ];

        $features = [
            "the comprehensive demo games section",
            "the RTP data accuracy",
            "real-time RTP tracking",
            "provider performance analytics",
            "the hot & fresh games section",
            "detailed game analytics",
            "the community testimonials",
            "the vast collection of gaming tools",
            "the comprehensive game database",
            "the premium features",
            "the real-time slot machine data",
            "the accurate RTP percentage tracking",
            "the provider comparison tools",
            "the live casino game statistics",
            "the tournament ranking system",
            "the advanced betting calculators",
            "the jackpot tracking features",
            "the bonus hunting tools",
            "the strategy optimization guides",
            "the risk assessment algorithms",
            "the game volatility analysis",
            "the payout frequency monitoring",
            "the mathematical advantage calculations",
            "the progressive jackpot tracking",
            "the seasonal promotion alerts",
            "the player loyalty program data",
            "the game fairness verification",
            "the historical performance charts",
            "the real-time win/loss statistics",
            "the betting pattern analysis",
            "the optimal bet sizing tools",
            "the game session optimization",
            "the bankroll management features",
            "the variance calculation tools",
            "the hit frequency tracking",
            "the RTP variance analysis",
            "the game selection algorithms",
            "the bonus feature probabilities",
            "the scatter symbol tracking",
            "the wild symbol optimization",
            "the free spin statistics",
            "the multiplier effect tracking",
            "the cascading reel analysis",
            "the cluster pay mechanics",
            "the buy feature analysis",
            "the gamble feature tracking",
            "the autoplay optimization",
            "the loss limit settings",
            "the win goal automation",
            "the session time tracking",
            "the profit/loss monitoring",
            "the ROI calculation tools",
            "the expected value computations",
            "the house edge analysis",
            "the optimal strategy guides",
            "the pattern recognition tools",
            "the hot streak detection",
            "the cold streak warnings",
            "the game cycle analysis",
            "the RTP fluctuation tracking",
            "the seasonal RTP changes",
            "the provider RTP consistency",
            "the game update tracking",
            "the new game alerts",
            "the popular game rankings",
            "the player favorite tracking",
            "the community rating system",
            "the expert review summaries",
            "the user experience ratings",
            "the game difficulty assessments",
            "the skill-based game analysis",
            "the luck factor calculations",
            "the progressive multiplier tracking",
            "the mystery bonus analysis",
            "the collectible feature tracking",
            "the achievement system data",
            "the leaderboard statistics",
            "the tournament performance data",
            "the seasonal event tracking",
            "the limited time offers",
            "the promotional RTP boosts",
            "the loyalty reward tracking",
            "the VIP program benefits",
            "the cashback offer analysis",
            "the reload bonus tracking",
            "the free bet opportunities",
            "the risk-free bet features",
            "the insurance bet options",
            "the hedging strategy tools",
            "the arbitrage opportunity detection",
            "the cross-game betting analysis",
            "the portfolio diversification tools",
            "the multi-game session management",
            "the automated betting systems",
            "the AI-powered recommendations",
            "the machine learning predictions",
            "the neural network analysis",
            "the big data processing capabilities",
            "the cloud-based analytics",
            "the mobile optimization features",
            "the cross-platform synchronization",
            "the real-time notification system",
            "the personalized dashboard",
            "the custom report generation",
            "the advanced filtering options",
            "the data export capabilities",
            "the API integration features",
            "the third-party tool compatibility",
            "the custom script execution",
            "the automated testing tools",
            "the performance benchmarking",
            "the comparative analysis features",
            "the historical data archives",
            "the trend analysis tools",
            "the predictive modeling",
            "the forecasting algorithms",
            "the statistical significance testing",
            "the confidence interval calculations",
            "the margin of error analysis",
            "the sample size optimization",
            "the data validation tools",
            "the anomaly detection systems"
        ];

        $benefits = [
            "helps me make informed decisions",
            "gives me a competitive edge",
            "improves my win rate significantly",
            "keeps me updated with the latest games",
            "is perfect for practicing strategies safely",
            "provides valuable insights for beginners",
            "makes this platform worth every penny",
            "has become essential to my gaming routine",
            "provides the most reliable information",
            "offers everything I need in one place",
            "maximizes my gaming potential",
            "saves me countless hours of research",
            "gives me confidence in my betting decisions",
            "helps me avoid costly mistakes",
            "provides edge over casual players",
            "optimizes my bankroll management",
            "increases my overall profitability",
            "reduces my gaming risks significantly",
            "enhances my strategic thinking",
            "keeps me ahead of the competition",
            "provides data-driven insights",
            "eliminates guesswork from gaming",
            "maximizes my entertainment value",
            "helps me achieve consistent results",
            "provides professional-grade analysis",
            "transforms my gaming approach",
            "gives me peace of mind",
            "enhances my gaming experience",
            "provides accurate statistical data",
            "helps me understand game mechanics",
            "optimizes my playing sessions",
            "provides real-time strategic guidance",
            "maximizes my winning opportunities",
            "minimizes my losses effectively",
            "provides comprehensive market analysis",
            "helps me identify profitable trends",
            "gives me access to expert knowledge",
            "provides personalized recommendations",
            "enhances my decision-making process",
            "gives me a mathematical advantage",
            "provides detailed performance metrics",
            "helps me track my progress",
            "optimizes my time investment",
            "provides actionable intelligence",
            "enhances my competitive skills",
            "gives me professional insights",
            "provides comprehensive coverage",
            "helps me stay informed",
            "maximizes my learning potential",
            "provides expert-level analysis",
            "gives me strategic advantages",
            "optimizes my gaming sessions",
            "provides detailed market intelligence",
            "helps me achieve my goals",
            "gives me confidence in my choices",
            "provides superior performance data",
            "enhances my gaming knowledge",
            "gives me access to premium content",
            "provides comprehensive statistics",
            "helps me understand complex games",
            "optimizes my betting strategy",
            "provides real-time market data",
            "maximizes my entertainment options",
            "gives me professional tools",
            "provides accurate trend analysis",
            "helps me avoid common pitfalls",
            "gives me a competitive advantage",
            "provides detailed game analysis",
            "enhances my winning potential",
            "gives me expert recommendations",
            "provides comprehensive insights",
            "helps me make better choices",
            "gives me strategic intelligence",
            "optimizes my gaming experience",
            "provides professional analytics",
            "helps me achieve success",
            "gives me access to exclusive data",
            "provides detailed performance analysis",
            "enhances my gaming skills",
            "gives me real-time updates",
            "provides comprehensive coverage",
            "helps me maximize profits",
            "gives me professional guidance",
            "provides accurate market data",
            "enhances my decision making",
            "gives me access to expert tools",
            "provides detailed statistics",
            "helps me understand market trends",
            "gives me strategic insights",
            "optimizes my investment",
            "provides real-time intelligence",
            "helps me achieve optimal results",
            "gives me professional advantages",
            "provides comprehensive analysis",
            "enhances my gaming performance",
            "gives me access to premium features",
            "provides detailed market insights",
            "helps me make informed investments",
            "gives me competitive intelligence",
            "provides expert-level guidance",
            "optimizes my gaming strategy",
            "gives me access to exclusive tools"
        ];

        $closings = [
            "Highly recommended!",
            "The customer support is also top-notch.",
            "This is a game-changer for serious gamers.",
            "My gaming experience has improved tremendously.",
            "I couldn't be happier with this platform.",
            "This platform exceeds all expectations.",
            "Every serious gamer should use this.",
            "The premium features are worth the investment.",
            "This has become my go-to gaming platform.",
            "I highly recommend it to all gamers.",
            "This platform has changed everything for me!",
            "I'm completely satisfied with this investment.",
            "The results speak for themselves.",
            "This is exactly what I was looking for.",
            "I can see the difference in my gaming results.",
            "The quality is outstanding throughout.",
            "This platform delivers on all promises.",
            "I'm impressed by every aspect of it.",
            "The attention to detail is remarkable.",
            "This has exceeded my expectations completely.",
            "I'm a customer for life now.",
            "The value for money is incredible.",
            "This platform has revolutionized gaming.",
            "I'm amazed by the comprehensive features.",
            "The user experience is flawless.",
            "This is a must-have for serious gamers.",
            "The professional quality is evident everywhere.",
            "I'm thoroughly impressed with everything.",
            "This platform has transformed my approach.",
            "The results are simply outstanding.",
            "I'm completely converted to this platform.",
            "The investment has paid off tremendously.",
            "This is the future of gaming platforms.",
            "I'm impressed by the depth of features.",
            "The quality exceeds industry standards.",
            "This platform has become indispensable.",
            "I'm amazed by the comprehensive coverage.",
            "The attention to user needs is exceptional.",
            "This is a game-changer in every way.",
            "I'm completely satisfied with the results.",
            "The professional approach is evident.",
            "This platform has exceeded all my hopes.",
            "I'm impressed by the consistent quality.",
            "The user-focused design is perfect.",
            "This is exactly what gamers need today.",
            "The comprehensive nature is impressive.",
            "I'm thoroughly pleased with everything.",
            "This platform has changed my gaming life.",
            "The results are better than expected.",
            "I'm completely won over by this platform.",
            "The investment is completely justified.",
            "This is the standard for gaming platforms.",
            "I'm impressed by the innovative features.",
            "The quality is unmatched in the industry.",
            "This platform has become essential to me.",
            "I'm amazed by the depth of analysis.",
            "The user experience is exceptional.",
            "This is a must-have tool for gamers.",
            "The professional standards are maintained.",
            "I'm thoroughly impressed with the platform.",
            "This platform has transformed gaming.",
            "The results are consistently excellent.",
            "I'm completely satisfied with the service.",
            "The comprehensive approach works perfectly.",
            "This platform has exceeded industry standards.",
            "I'm impressed by the innovative design.",
            "The quality is evident in every detail.",
            "This platform has become my favorite.",
            "I'm amazed by the comprehensive features.",
            "The user-centric approach is perfect.",
            "This is the best gaming platform available.",
            "The professional quality is outstanding.",
            "I'm thoroughly pleased with the investment.",
            "This platform has changed my perspective.",
            "The results are simply remarkable.",
            "I'm completely converted to this service.",
            "The value provided is exceptional.",
            "This is the future of gaming analytics.",
            "I'm impressed by the depth of insights.",
            "The quality standards are exemplary.",
            "This platform has become indispensable.",
            "I'm amazed by the comprehensive database.",
            "The attention to user experience is perfect.",
            "This is a game-changer for the industry.",
            "I'm completely satisfied with the quality.",
            "The professional approach is flawless.",
            "This platform has exceeded my expectations.",
            "I'm impressed by the consistent excellence.",
            "The user-focused features are excellent.",
            "This is exactly what modern gamers need.",
            "The comprehensive coverage is impressive.",
            "I'm thoroughly impressed with the results.",
            "This platform has transformed my gaming.",
            "The investment has been completely worthwhile.",
            "I'm completely won over by the platform.",
            "The quality is unmatched anywhere.",
            "This platform has become my standard.",
            "I'm amazed by the innovative approach.",
            "The professional standards are perfect.",
            "This is a must-have for any gamer.",
            "The comprehensive nature is outstanding.",
            "I'm thoroughly pleased with the platform.",
            "This platform has changed everything.",
            "The results are consistently impressive.",
            "I'm completely satisfied with the features.",
            "The comprehensive approach is excellent.",
            "This platform has set new standards.",
            "I'm impressed by the innovative features.",
            "The quality is evident throughout.",
            "This platform has become essential.",
            "I'm amazed by the depth of features."
        ];

        $testimonialMessages = [];
        for ($i = 0; $i < $count; $i++) {
            $opening = $openings[array_rand($openings)];
            $feature = $features[array_rand($features)];
            $benefit = $benefits[array_rand($benefits)];
            $closing = $closings[array_rand($closings)];

            $message = $opening . " " . $feature . " " . $benefit . " " . $closing;
            $testimonialMessages[] = $message;
        }

        return $testimonialMessages;
    }
}
